version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
  spring-boot-jpa-docker-webapp:
    image: gradle-springboot
    depends_on:
      - sr03-project-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=sr03-project
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=sr03-project-db
      - DATABASE_PORT=3306
